// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainTicketApi.Data;

#nullable disable

namespace TrainTicketApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505082112_InitTrainTicketManagement")]
    partial class InitTrainTicketManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainTicketApi.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Ha Noi",
                            Email = "nguyenvana@example.com",
                            FullName = "Nguyen Van A",
                            IdentityNumber = "012345678901",
                            PhoneNumber = "0912345678"
                        });
                });

            modelBuilder.Entity("TrainTicketApi.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TicketStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TrainTripId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.HasIndex("TrainTripId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_Price", "[Price] > 0");
                        });

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            BookingDate = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            PaymentStatus = "Paid",
                            Price = 180000m,
                            SeatNumber = "A01",
                            TicketCode = "TICKET-20260501-0001",
                            TicketStatus = "Booked",
                            TrainTripId = 1
                        });
                });

            modelBuilder.Entity("TrainTicketApi.Models.TrainRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("ArrivalStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RouteId");

                    b.ToTable("Routes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Routes_DistanceKm", "[DistanceKm] > 0");
                        });

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            ArrivalStation = "Hai Phong",
                            DepartureStation = "Ha Noi",
                            DistanceKm = 102m,
                            Status = "Active"
                        },
                        new
                        {
                            RouteId = 2,
                            ArrivalStation = "Da Nang",
                            DepartureStation = "Ha Noi",
                            DistanceKm = 764m,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TrainTicketApi.Models.TrainTrip", b =>
                {
                    b.Property<int>("TrainTripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainTripId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseTicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TrainTripId");

                    b.HasIndex("RouteId");

                    b.HasIndex("TrainCode");

                    b.ToTable("TrainTrips", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrainTrips_ArrivalTime", "[ArrivalTime] > [DepartureTime]");

                            t.HasCheckConstraint("CK_TrainTrips_AvailableSeats", "[AvailableSeats] >= 0 AND [AvailableSeats] <= [TotalSeats]");

                            t.HasCheckConstraint("CK_TrainTrips_BaseTicketPrice", "[BaseTicketPrice] > 0");

                            t.HasCheckConstraint("CK_TrainTrips_TotalSeats", "[TotalSeats] > 0");
                        });

                    b.HasData(
                        new
                        {
                            TrainTripId = 1,
                            ArrivalTime = new DateTime(2026, 6, 1, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 119,
                            BaseTicketPrice = 180000m,
                            DepartureTime = new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 1,
                            Status = "Scheduled",
                            TotalSeats = 120,
                            TrainCode = "SE01"
                        },
                        new
                        {
                            TrainTripId = 2,
                            ArrivalTime = new DateTime(2026, 6, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            AvailableSeats = 200,
                            BaseTicketPrice = 850000m,
                            DepartureTime = new DateTime(2026, 6, 2, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 2,
                            Status = "Scheduled",
                            TotalSeats = 200,
                            TrainCode = "SE03"
                        });
                });

            modelBuilder.Entity("TrainTicketApi.Models.Ticket", b =>
                {
                    b.HasOne("TrainTicketApi.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrainTicketApi.Models.TrainTrip", "TrainTrip")
                        .WithMany("Tickets")
                        .HasForeignKey("TrainTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TrainTrip");
                });

            modelBuilder.Entity("TrainTicketApi.Models.TrainTrip", b =>
                {
                    b.HasOne("TrainTicketApi.Models.TrainRoute", "Route")
                        .WithMany("TrainTrips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TrainTicketApi.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TrainTicketApi.Models.TrainRoute", b =>
                {
                    b.Navigation("TrainTrips");
                });

            modelBuilder.Entity("TrainTicketApi.Models.TrainTrip", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
